import type { Character } from '@/types/character';

export const DEV_SEED_CHARACTERS: Character[] = [
  {
    id: 'seed-1',
    version: '1.0.0',
    name: 'Thendrin Ashwood',
    race: 'Elf',
    subrace: 'High Elf',
    class: 'Wizard',
    background: 'Sage',
    level: 5,
    experiencePoints: 6500,
    abilityScores: {
      strength: 8,
      dexterity: 14,
      constitution: 12,
      intelligence: 18,
      wisdom: 13,
      charisma: 10,
    },
    proficiencyBonus: 3,
    proficiencies: {
      armor: [],
      weapons: [
        'Daggers',
        'Darts',
        'Slings',
        'Quarterstaffs',
        'Light Crossbows',
      ],
      tools: [],
      languages: ['Common', 'Elvish', 'Draconic', 'Dwarvish'],
      savingThrows: ['Intelligence', 'Wisdom'],
    },
    features: [
      {
        id: 'f-wizard-arcane-recovery',
        name: 'Arcane Recovery',
        source: 'Wizard',
        description:
          'Once per day when you finish a short rest, recover spell slots with total level ≤ half wizard level (rounded up).',
        level: 1,
      },
      {
        id: 'f-wizard-spellbook',
        name: 'Spellbook',
        source: 'Wizard',
        description: 'You have a spellbook containing 14 spells.',
        level: 1,
      },
      {
        id: 'f-wizard-evocation',
        name: 'Evocation Savant',
        source: 'Wizard (School of Evocation)',
        description:
          'The gold and time you spend to copy an Evocation spell into your spellbook is halved.',
        level: 2,
      },
      {
        id: 'f-wizard-sculpt-spells',
        name: 'Sculpt Spells',
        source: 'Wizard (School of Evocation)',
        description:
          'Create pockets of relative safety within the effects of your Evocation spells. Choose up to wizard level ÷ 3 + 1 targets to automatically succeed saving throws and take no damage.',
        level: 2,
      },
    ],
    feats: [],
    spells: {
      spellcastingAbility: 'Intelligence',
      spellSaveDC: 15,
      spellAttackBonus: 7,
      cantrips: [
        'Fire Bolt',
        'Mage Hand',
        'Prestidigitation',
        'Shocking Grasp',
      ],
      spellsKnown: [
        'Burning Hands',
        'Detect Magic',
        'Magic Missile',
        'Shield',
        'Misty Step',
        'Scorching Ray',
        'Web',
        'Counterspell',
        'Fireball',
        'Fly',
      ],
      spellSlots: {
        level1: { max: 4, used: 0 },
        level2: { max: 3, used: 0 },
        level3: { max: 2, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
      preparedSpells: [
        'Burning Hands',
        'Magic Missile',
        'Shield',
        'Misty Step',
        'Scorching Ray',
        'Fireball',
        'Fly',
      ],
    },
    equipment: [
      {
        id: 'eq-1',
        name: 'Quarterstaff',
        type: 'Weapon',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-2',
        name: 'Spellbook',
        type: 'Gear',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-3',
        name: 'Component Pouch',
        type: 'Gear',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-4',
        name: "Scholar's Pack",
        type: 'Gear',
        quantity: 1,
        equipped: false,
      },
      {
        id: 'eq-5',
        name: 'Scroll of Identify',
        type: 'Consumable',
        quantity: 2,
        equipped: false,
      },
    ],
    hitPoints: { max: 28, current: 28, temporary: 0 },
    armorClass: 13,
    initiative: 2,
    speed: 30,
    savingThrows: {
      strength: { proficient: false, bonus: -1 },
      dexterity: { proficient: false, bonus: 2 },
      constitution: { proficient: false, bonus: 1 },
      intelligence: { proficient: true, bonus: 7 },
      wisdom: { proficient: true, bonus: 4 },
      charisma: { proficient: false, bonus: 0 },
    },
    skills: {
      Arcana: { proficient: true, expertise: false, bonus: 7 },
      History: { proficient: true, expertise: false, bonus: 7 },
      Investigation: { proficient: true, expertise: false, bonus: 7 },
      Medicine: { proficient: true, expertise: false, bonus: 4 },
    },
    details: {
      gender: 'Male',
      alignment: 'Neutral Good',
      age: 132,
      height: '5\'11"',
      weight: '150 lbs',
      eyes: 'Silver',
      skin: 'Pale',
      hair: 'White',
      personalityTraits:
        'I use polysyllabic words that convey the impression of great erudition.',
      ideals: 'Knowledge is the path to power and dominance.',
      bonds:
        "My life's work is a series of tomes related to conjuration theory.",
      flaws: "I'm convinced that people are always trying to steal my secrets.",
      backstory:
        'Born in the high elven city of Silverymoon, Thendrin showed an early aptitude for the arcane arts. After a century of study, he left the city to seek ancient magical lore lost during the Spellplague.',
    },
    portrait: '/assets/images/characters/placeholder_char_card0.jpg',
    createdAt: '2026-01-01T00:00:00.000Z',
    lastModified: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'seed-2',
    version: '1.0.0',
    name: 'Seraphina Brightforge',
    race: 'Human',
    class: 'Fighter',
    background: 'Soldier',
    level: 4,
    experiencePoints: 2700,
    abilityScores: {
      strength: 17,
      dexterity: 12,
      constitution: 15,
      intelligence: 10,
      wisdom: 12,
      charisma: 10,
    },
    proficiencyBonus: 2,
    proficiencies: {
      armor: ['Light Armor', 'Medium Armor', 'Heavy Armor', 'Shields'],
      weapons: ['Simple Weapons', 'Martial Weapons'],
      tools: ['Dice Set', 'Vehicles (Land)'],
      languages: ['Common', 'Orc'],
      savingThrows: ['Strength', 'Constitution'],
    },
    features: [
      {
        id: 'f-fighter-second-wind',
        name: 'Second Wind',
        source: 'Fighter',
        description:
          'As a bonus action, regain 1d10 + fighter level HP. Recharges on short or long rest.',
        level: 1,
      },
      {
        id: 'f-fighter-action-surge',
        name: 'Action Surge',
        source: 'Fighter',
        description:
          'On your turn, take one additional action. Recharges on short or long rest.',
        level: 2,
      },
      {
        id: 'f-fighter-champion-improved-critical',
        name: 'Improved Critical',
        source: 'Fighter (Champion)',
        description:
          'Your weapon attacks score a critical hit on a roll of 19 or 20.',
        level: 3,
      },
      {
        id: 'f-fighter-extra-attack',
        name: 'Extra Attack',
        source: 'Fighter',
        description:
          'Attack twice whenever you take the Attack action on your turn.',
        level: 5,
      },
    ],
    feats: [
      {
        id: 'feat-grappler',
        name: 'Grappler',
        source: "Player's Handbook",
        description:
          'You have advantage on attack rolls against a creature you are grappling.',
        prerequisites: 'Strength 13 or higher',
      },
    ],
    spells: {
      cantrips: [],
      spellsKnown: [],
      spellSlots: {
        level1: { max: 0, used: 0 },
        level2: { max: 0, used: 0 },
        level3: { max: 0, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
      preparedSpells: [],
    },
    equipment: [
      {
        id: 'eq-10',
        name: 'Chain Mail',
        type: 'Armor',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-11',
        name: 'Shield',
        type: 'Armor',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-12',
        name: 'Longsword +1',
        type: 'Weapon',
        quantity: 1,
        equipped: true,
        description:
          'A finely balanced blade with a sapphire set in the pommel.',
      },
      {
        id: 'eq-13',
        name: 'Handaxe',
        type: 'Weapon',
        quantity: 2,
        equipped: false,
      },
      {
        id: 'eq-14',
        name: "Explorer's Pack",
        type: 'Gear',
        quantity: 1,
        equipped: false,
      },
      {
        id: 'eq-15',
        name: 'Healing Potion',
        type: 'Consumable',
        quantity: 2,
        equipped: false,
      },
    ],
    hitPoints: { max: 36, current: 36, temporary: 0 },
    armorClass: 19,
    initiative: 1,
    speed: 30,
    savingThrows: {
      strength: { proficient: true, bonus: 5 },
      dexterity: { proficient: false, bonus: 1 },
      constitution: { proficient: true, bonus: 4 },
      intelligence: { proficient: false, bonus: 0 },
      wisdom: { proficient: false, bonus: 1 },
      charisma: { proficient: false, bonus: 0 },
    },
    skills: {
      Athletics: { proficient: true, expertise: false, bonus: 5 },
      Intimidation: { proficient: true, expertise: false, bonus: 2 },
      Perception: { proficient: true, expertise: false, bonus: 3 },
      Survival: { proficient: true, expertise: false, bonus: 3 },
    },
    details: {
      gender: 'Female',
      alignment: 'Lawful Neutral',
      age: 28,
      height: '5\'8"',
      weight: '165 lbs',
      eyes: 'Hazel',
      skin: 'Tanned',
      hair: 'Auburn',
      personalityTraits:
        'I face problems head-on. A simple, direct solution is the best path.',
      ideals: 'Responsibility. I do what I must and obey just authority.',
      bonds: 'Those who fight beside me are worth dying for.',
      flaws:
        'I have a weakness for the vices of the city, especially strong drink.',
      backstory:
        "Serra served ten years in the Flaming Fist mercenary company before an incident in Baldur's Gate left her disillusioned with military life. Now she wanders, selling her blade where her conscience allows.",
    },
    portrait: '/assets/images/characters/placeholder_char_card4.jpg',
    createdAt: '2026-01-05T00:00:00.000Z',
    lastModified: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'seed-3',
    version: '1.0.0',
    name: 'Brindal Copperkettle',
    race: 'Halfling',
    subrace: 'Stout',
    class: 'Rogue',
    background: 'Criminal',
    level: 3,
    experiencePoints: 900,
    abilityScores: {
      strength: 10,
      dexterity: 17,
      constitution: 14,
      intelligence: 12,
      wisdom: 10,
      charisma: 11,
    },
    proficiencyBonus: 2,
    proficiencies: {
      armor: ['Light Armor'],
      weapons: [
        'Simple Weapons',
        'Hand Crossbows',
        'Longswords',
        'Rapiers',
        'Shortswords',
      ],
      tools: ["Thieves' Tools", 'Dice Set'],
      languages: ['Common', 'Halfling'],
      savingThrows: ['Dexterity', 'Intelligence'],
    },
    features: [
      {
        id: 'f-rogue-expertise',
        name: 'Expertise',
        source: 'Rogue',
        description:
          "Double your proficiency bonus for Stealth and Thieves' Tools.",
        level: 1,
      },
      {
        id: 'f-rogue-sneak-attack',
        name: 'Sneak Attack',
        source: 'Rogue',
        description:
          'Deal extra 2d6 damage to one creature per turn when you have advantage or an ally is adjacent to the target.',
        level: 1,
      },
      {
        id: 'f-rogue-cunning-action',
        name: 'Cunning Action',
        source: 'Rogue',
        description: 'Bonus action to Dash, Disengage, or Hide.',
        level: 2,
      },
      {
        id: 'f-rogue-arcane-trickster',
        name: 'Mage Hand Legerdemain',
        source: 'Rogue (Arcane Trickster)',
        description:
          'Your Mage Hand is invisible and can pick locks and pick pockets.',
        level: 3,
      },
    ],
    feats: [],
    spells: {
      spellcastingAbility: 'Intelligence',
      spellSaveDC: 11,
      spellAttackBonus: 3,
      cantrips: ['Mage Hand', 'Minor Illusion'],
      spellsKnown: ['Charm Person', 'Silent Image'],
      spellSlots: {
        level1: { max: 2, used: 0 },
        level2: { max: 0, used: 0 },
        level3: { max: 0, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
      preparedSpells: ['Charm Person', 'Silent Image'],
    },
    equipment: [
      {
        id: 'eq-20',
        name: 'Leather Armor',
        type: 'Armor',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-21',
        name: 'Rapier',
        type: 'Weapon',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-22',
        name: 'Hand Crossbow',
        type: 'Weapon',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-23',
        name: 'Crossbow Bolts',
        type: 'Ammo',
        quantity: 20,
        equipped: false,
      },
      {
        id: 'eq-24',
        name: "Thieves' Tools",
        type: 'Tool',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-25',
        name: 'Dark Common Clothes',
        type: 'Gear',
        quantity: 1,
        equipped: true,
      },
      {
        id: 'eq-26',
        name: "Healer's Kit",
        type: 'Gear',
        quantity: 1,
        equipped: false,
      },
    ],
    hitPoints: { max: 22, current: 22, temporary: 0 },
    armorClass: 14,
    initiative: 3,
    speed: 25,
    savingThrows: {
      strength: { proficient: false, bonus: 0 },
      dexterity: { proficient: true, bonus: 5 },
      constitution: { proficient: false, bonus: 2 },
      intelligence: { proficient: true, bonus: 3 },
      wisdom: { proficient: false, bonus: 0 },
      charisma: { proficient: false, bonus: 0 },
    },
    skills: {
      Acrobatics: { proficient: true, expertise: false, bonus: 5 },
      Deception: { proficient: true, expertise: false, bonus: 2 },
      Perception: { proficient: true, expertise: false, bonus: 2 },
      Sleight_of_Hand: { proficient: true, expertise: false, bonus: 5 },
      Stealth: { proficient: true, expertise: true, bonus: 7 },
    },
    details: {
      gender: 'Male',
      alignment: 'Chaotic Neutral',
      age: 34,
      height: '3\'1"',
      weight: '38 lbs',
      eyes: 'Brown',
      skin: 'Olive',
      hair: 'Curly Black',
      personalityTraits:
        'I always have a plan for what to do when things go wrong.',
      ideals: 'Freedom. Chains are meant to be broken.',
      bonds:
        "I'm trying to pay off an old debt I owe to a generous halfling who gave me a chance.",
      flaws:
        "When I see something valuable, I can't think about anything but how to steal it.",
      backstory:
        'Raised in the back alleys of Waterdeep, Brindal learned to survive by his wits and nimble fingers. A chance encounter with a street magician opened his eyes to the arcane, and he now blends sleight-of-hand with genuine spellcraft.',
    },
    portrait: '/assets/images/characters/placeholder_char_card7.jpg',
    createdAt: '2026-01-10T00:00:00.000Z',
    lastModified: '2026-01-10T00:00:00.000Z',
  },
];
