import { SOURCE_PRESETS } from '@/lib/sourcePresets'
import type { Character, ProvenanceLedger } from '@/types/character'

const RECOMMENDED_SOURCES = [
  ...(SOURCE_PRESETS.find((preset) => preset.id === '2014-recommended')?.abbreviations ?? [
    'PHB',
    'XGE',
    'TCE',
    'MPMM',
    'ERLW',
    'EGW',
    'MOT',
    'VRGR',
  ]),
]

const ALL_BOOK_SOURCES = [
  'AAG',
  'AATM',
  'ABH',
  'AI',
  'AL',
  'AWM',
  'BAM',
  'BGG',
  'BMT',
  'DMG',
  'DMTCRG',
  'DoD',
  'EFA',
  'EGW',
  'ERLW',
  'FRAiF',
  'FRHoF',
  'FTD',
  'GGR',
  'HAT-TG',
  'HF',
  'HFFotM',
  'LFL',
  'MaBJoV',
  'MCV4EC',
  'MGELFT',
  'MM',
  'MOT',
  'MPMM',
  'MPP',
  'MTF',
  'NF',
  'OGA',
  'PaF',
  'PHB',
  'PSA',
  'PSD',
  'PSI',
  'PSK',
  'PSX',
  'PSZ',
  'RMR',
  'SAC',
  'SatO',
  'SCAG',
  'SCC',
  'Screen',
  'ScreenDungeonKit',
  'ScreenSpelljammer',
  'ScreenWildernessKit',
  'TCE',
  'TD',
  'VGM',
  'VRGR',
  'XDMG',
  'XGE',
  'XMM',
  'XPHB',
  'XSAC',
  'XScreen',
]

const createEmptyProvenance = (): ProvenanceLedger => {
  const emptyMap = () => ({}) as Record<string, never[]>

  return {
    proficiencies: {
      armor: emptyMap(),
      weapons: emptyMap(),
      tools: emptyMap(),
      languages: emptyMap(),
      skills: emptyMap(),
      savingThrows: emptyMap(),
    },
    abilityBonuses: [],
    features: emptyMap(),
    feats: emptyMap(),
    spells: emptyMap(),
    equipment: emptyMap(),
    choices: [],
  }
}

const classSpellTag = (
  sourceName: string,
  sourceRef: string,
  spellGrantedAtLevel: number,
  spellAttributionMode: 'exact' | 'inferred-lowest-eligible' = 'exact',
) => ({
  sourceType: 'class' as const,
  sourceName,
  sourceRef,
  grantType: 'choice' as const,
  label: sourceName,
  spellGrantedAtLevel,
  spellAttributionMode,
})

const BASE_TIME = '2026-04-06T00:00:00.000Z'

export const DEV_SEED_CHARACTERS: Character[] = [
  {
    id: 'seed-1',
    version: '1.0.0',
    name: 'Seraphina Vale',
    race: 'Human',
    raceSource: 'PHB',
    class: 'Wizard',
    classSource: 'PHB',
    subclass: 'School of Evocation',
    subclassSource: 'PHB',
    background: 'Acolyte',
    backgroundSource: 'PHB',
    level: 5,
    experiencePoints: 6500,
    classProgression: [
      {
        name: 'Wizard',
        source: 'PHB',
        levels: 5,
        subclass: 'School of Evocation',
        subclassSource: 'PHB',
      },
    ],
    abilityScores: {
      strength: 8,
      dexterity: 14,
      constitution: 14,
      intelligence: 14,
      wisdom: 12,
      charisma: 10,
    },
    proficiencies: {
      armor: [],
      weapons: ['Daggers', 'Darts', 'Slings', 'Quarterstaffs', 'Light Crossbows'],
      tools: [],
      skills: [],
      languages: ['Common', 'Celestial', 'Elvish'],
      savingThrows: ['Intelligence', 'Wisdom'],
    },
    features: [
      {
        id: 'wiz-arcane-recovery',
        name: 'Arcane Recovery',
        source: 'Wizard',
        description:
          'Recover expended spell slots up to a combined level of 3 after a short rest once per day.',
        level: 1,
      },
      {
        id: 'wiz-spellbook',
        name: 'Spellbook',
        source: 'Wizard',
        description: 'Maintains a fully curated spellbook through 3rd-level spells.',
        level: 1,
      },
      {
        id: 'evoc-savant',
        name: 'Evocation Savant',
        source: 'Wizard (School of Evocation)',
        description: 'Copying evocation spells into the spellbook costs half time and gold.',
        level: 2,
      },
      {
        id: 'sculpt-spells',
        name: 'Sculpt Spells',
        source: 'Wizard (School of Evocation)',
        description:
          'Allies can automatically succeed on saves against your evocation spells and take no damage.',
        level: 2,
      },
      {
        id: 'asi-wiz4',
        name: 'Ability Score Improvement',
        source: 'Wizard',
        description: 'Took +2 Intelligence at wizard level 4.',
        level: 4,
      },
    ],
    feats: [],
    spells: {
      spellProfiles: [
        {
          id: 'class:Wizard|PHB',
          type: 'class',
          label: 'Wizard (Lv 5)',
          className: 'Wizard',
          classSource: 'PHB',
          cantrips: ['Fire Bolt', 'Mage Hand', 'Minor Illusion', 'Prestidigitation'],
          spellsKnown: [
            'Shield',
            'Mage Armor',
            'Magic Missile',
            'Find Familiar',
            'Detect Magic',
            'Sleep',
            'Feather Fall',
            'Charm Person',
            'Misty Step',
            'Scorching Ray',
            'Mirror Image',
            'Invisibility',
            'Fireball',
            'Counterspell',
          ],
          preparedSpells: ['Shield', 'Mage Armor', 'Magic Missile', 'Fireball'],
        },
        {
          id: 'special:unrestricted',
          type: 'special',
          label: 'Special (Unrestricted)',
          cantrips: [],
          spellsKnown: [],
          preparedSpells: [],
          alwaysPrepared: true,
        },
      ],
      spellSlots: {
        level1: { max: 4, used: 0 },
        level2: { max: 3, used: 0 },
        level3: { max: 2, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
    },
    equipment: [
      {
        id: 's1-eq1',
        name: 'Quarterstaff',
        type: 'M',
        quantity: 1,
        equipped: true,
      },
      {
        id: 's1-eq2',
        name: 'Spellbook',
        type: 'G',
        quantity: 1,
        equipped: true,
        source: 'PHB',
      },
      {
        id: 's1-eq3',
        name: 'Component Pouch',
        type: 'G',
        quantity: 1,
        equipped: true,
        source: 'PHB',
      },
    ],
    hitPoints: { max: 27, current: 27, temporary: 0 },
    armorClass: 13,
    initiative: 2,
    speed: 30,
    savingThrows: {
      strength: { proficient: false, bonus: -1 },
      dexterity: { proficient: false, bonus: 2 },
      constitution: { proficient: false, bonus: 2 },
      intelligence: { proficient: true, bonus: 6 },
      wisdom: { proficient: true, bonus: 4 },
      charisma: { proficient: false, bonus: 0 },
    },
    skills: {
      arcana: { proficient: true, expertise: false, bonus: 6 },
      history: { proficient: true, expertise: false, bonus: 6 },
      insight: { proficient: true, expertise: false, bonus: 4 },
      religion: { proficient: true, expertise: false, bonus: 6 },
    },
    details: {
      gender: 'Female',
      alignment: 'Lawful Good',
      faith: 'Mystra',
      lifestyle: 'Modest',
      personalityTraits: 'I am calm under pressure and speak with deliberate precision.',
      ideals: 'Knowledge and compassion should guide power.',
      bonds: 'My temple library entrusted me with preserving dangerous lore responsibly.',
      flaws: 'I struggle to delegate when arcane details are at stake.',
      goals: 'Recover lost fragments of the Codex of Embers.',
      fears: 'That my magic harms innocents through my own carelessness.',
      age: 28,
      height: '5\'7"',
      weight: '138 lbs',
      eyes: 'Hazel',
      skin: 'Olive',
      hair: 'Black',
      physicalDescription: 'Travel robes lined with scripture sigils and ash-gray trim.',
      mannerisms: 'Thumb taps twice against her spellbook before casting.',
      origin: 'Raised in a cloister known for preserving magical history.',
      family: 'Youngest of four siblings, first to enter formal arcane study.',
      definingMoment: 'Contained a chapel fire with an improvised ward at age sixteen.',
      lifeEvents: 'Completed a decade apprenticeship and served as temple archivist.',
      backstory:
        'Seraphina trained as an acolyte before embracing wizardry, convinced that arcane study and faith can coexist. She now travels to recover dangerous texts before they are misused.',
      alliesAndOrganizations: 'Order of the Sapphire Torch; High Archivist Meliora.',
    },
    portrait: '/assets/images/characters/placeholder_char_card.jpg',
    allowedSources: RECOMMENDED_SOURCES,
    variantRules: {
      optionalClassFeatures: true,
      averageHitPoints: true,
      abilityScoreMethod: 'point-buy',
    },
    asiChoices: [
      {
        id: 'seed-1-asi-4',
        level: 4,
        className: 'Wizard',
        abilityChanges: { intelligence: 2 },
      },
    ],
    provenance: {
      ...createEmptyProvenance(),
      proficiencies: {
        armor: {},
        weapons: {
          daggers: [
            {
              sourceType: 'class',
              sourceName: 'Wizard',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Wizard',
            },
          ],
        },
        tools: {},
        languages: {
          common: [
            {
              sourceType: 'race',
              sourceName: 'Human',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Human',
            },
          ],
          celestial: [
            {
              sourceType: 'background',
              sourceName: 'Acolyte',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Acolyte',
            },
          ],
          elvish: [
            {
              sourceType: 'background',
              sourceName: 'Acolyte',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Acolyte',
            },
          ],
        },
        skills: {
          arcana: [
            {
              sourceType: 'class',
              sourceName: 'Wizard',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Wizard',
            },
          ],
          religion: [
            {
              sourceType: 'background',
              sourceName: 'Acolyte',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Acolyte',
            },
          ],
        },
        savingThrows: {
          intelligence: [
            {
              sourceType: 'class',
              sourceName: 'Wizard',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Wizard',
            },
          ],
          wisdom: [
            {
              sourceType: 'class',
              sourceName: 'Wizard',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Wizard',
            },
          ],
        },
      },
      abilityBonuses: [
        {
          ability: 'strength',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'dexterity',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'constitution',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'intelligence',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'wisdom',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'charisma',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Human',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Human',
          },
        },
        {
          ability: 'intelligence',
          value: 2,
          sourceTag: {
            sourceType: 'class',
            sourceName: 'Ability Score Improvement',
            sourceRef: 'PHB',
            grantType: 'choice',
            label: 'ASI',
          },
        },
      ],
      spells: {
        'fire bolt': [classSpellTag('Wizard', 'PHB', 1)],
        'mage hand': [classSpellTag('Wizard', 'PHB', 1)],
        'minor illusion': [classSpellTag('Wizard', 'PHB', 1)],
        prestidigitation: [classSpellTag('Wizard', 'PHB', 4)],
        shield: [classSpellTag('Wizard', 'PHB', 1)],
        'mage armor': [classSpellTag('Wizard', 'PHB', 1)],
        'magic missile': [classSpellTag('Wizard', 'PHB', 1)],
        'find familiar': [classSpellTag('Wizard', 'PHB', 1)],
        'detect magic': [classSpellTag('Wizard', 'PHB', 1)],
        sleep: [classSpellTag('Wizard', 'PHB', 1)],
        'feather fall': [classSpellTag('Wizard', 'PHB', 2)],
        'charm person': [classSpellTag('Wizard', 'PHB', 2)],
        'misty step': [classSpellTag('Wizard', 'PHB', 3)],
        'scorching ray': [classSpellTag('Wizard', 'PHB', 3)],
        'mirror image': [classSpellTag('Wizard', 'PHB', 4)],
        invisibility: [classSpellTag('Wizard', 'PHB', 4)],
        fireball: [classSpellTag('Wizard', 'PHB', 5)],
        counterspell: [classSpellTag('Wizard', 'PHB', 5)],
      },
      features: {
        'arcane recovery': [
          {
            sourceType: 'class',
            sourceName: 'Wizard',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Wizard',
          },
        ],
      },
    },
    createdAt: BASE_TIME,
    lastModified: BASE_TIME,
  },
  {
    id: 'seed-2',
    version: '1.0.0',
    name: 'Bromm Ironvein',
    race: 'Dwarf',
    raceSource: 'XPHB',
    class: 'Fighter',
    classSource: 'XPHB',
    subclass: 'Battle Master',
    subclassSource: 'XPHB',
    background: 'Soldier',
    backgroundSource: 'XPHB',
    level: 5,
    experiencePoints: 6500,
    classProgression: [
      {
        name: 'Fighter',
        source: 'XPHB',
        levels: 5,
        subclass: 'Battle Master',
        subclassSource: 'XPHB',
      },
    ],
    abilityScores: {
      strength: 15,
      dexterity: 13,
      constitution: 14,
      intelligence: 8,
      wisdom: 12,
      charisma: 10,
    },
    proficiencies: {
      armor: ['light', 'medium', 'heavy', 'shield'],
      weapons: ['simple', 'martial'],
      tools: ["Smith's Tools"],
      skills: [],
      languages: ['Common', 'Dwarvish', 'Giant'],
      savingThrows: ['Strength', 'Constitution'],
    },
    features: [
      {
        id: 'fighting-style-defense',
        name: 'Fighting Style (Defense)',
        source: 'Fighter',
        description: 'Gain +1 AC while wearing armor.',
        level: 1,
      },
      {
        id: 'second-wind',
        name: 'Second Wind',
        source: 'Fighter',
        description: 'Recover hit points as a bonus action once per short rest.',
        level: 1,
      },
      {
        id: 'action-surge',
        name: 'Action Surge',
        source: 'Fighter',
        description: 'Take one additional action on your turn once per short rest.',
        level: 2,
      },
      {
        id: 'combat-superiority',
        name: 'Combat Superiority',
        source: 'Fighter (Battle Master)',
        description:
          'Superiority dice and maneuvers selected: Precision Attack, Trip Attack, Menacing Attack.',
        level: 3,
      },
      {
        id: 'student-of-war',
        name: 'Student of War',
        source: 'Fighter (Battle Master)',
        description: "Additional artisan tool proficiency selected: Smith's Tools.",
        level: 3,
      },
      {
        id: 'asi-ftr4',
        name: 'Ability Score Improvement',
        source: 'Fighter',
        description: 'Took +2 Strength at fighter level 4.',
        level: 4,
      },
      {
        id: 'extra-attack',
        name: 'Extra Attack',
        source: 'Fighter',
        description: 'Can attack twice, instead of once, whenever taking the Attack action.',
        level: 5,
      },
    ],
    feats: [],
    specialFeats: [
      {
        id: 'feat-fs-defense',
        name: 'Defense',
        source: 'XPHB',
        description: 'While you are wearing armor, you gain a +1 bonus to AC.',
      },
    ],
    spells: {
      spellProfiles: [
        {
          id: 'class:Fighter|XPHB',
          type: 'class',
          label: 'Fighter (Lv 5)',
          className: 'Fighter',
          classSource: 'XPHB',
          cantrips: [],
          spellsKnown: [],
          preparedSpells: [],
        },
        {
          id: 'special:unrestricted',
          type: 'special',
          label: 'Special (Unrestricted)',
          cantrips: [],
          spellsKnown: [],
          preparedSpells: [],
          alwaysPrepared: true,
        },
      ],
      spellSlots: {
        level1: { max: 0, used: 0 },
        level2: { max: 0, used: 0 },
        level3: { max: 0, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
    },
    equipment: [
      {
        id: 's2-eq1',
        name: 'Chain Mail',
        type: 'HA',
        quantity: 1,
        equipped: true,
        ac: 16,
        armorType: 'heavy',
      },
      {
        id: 's2-eq2',
        name: 'Shield',
        type: 'S',
        quantity: 1,
        equipped: true,
        ac: 2,
        armorType: 'shield',
      },
      {
        id: 's2-eq3',
        name: 'Longsword',
        type: 'M',
        quantity: 1,
        equipped: true,
      },
      {
        id: 's2-eq4',
        name: 'Handaxe',
        type: 'M',
        quantity: 2,
        equipped: false,
      },
    ],
    hitPoints: { max: 49, current: 49, temporary: 0 },
    armorClass: 19,
    initiative: 1,
    speed: 25,
    savingThrows: {
      strength: { proficient: true, bonus: 6 },
      dexterity: { proficient: false, bonus: 1 },
      constitution: { proficient: true, bonus: 5 },
      intelligence: { proficient: false, bonus: -1 },
      wisdom: { proficient: false, bonus: 1 },
      charisma: { proficient: false, bonus: 0 },
    },
    skills: {
      athletics: { proficient: true, expertise: false, bonus: 6 },
      intimidation: { proficient: true, expertise: false, bonus: 3 },
      perception: { proficient: true, expertise: false, bonus: 4 },
      survival: { proficient: true, expertise: false, bonus: 4 },
    },
    details: {
      gender: 'Male',
      alignment: 'Lawful Neutral',
      lifestyle: 'Modest',
      personalityTraits: 'I keep my gear immaculate and my oath plainspoken.',
      ideals: 'Discipline keeps people alive.',
      bonds: 'My old unit still sends me coded dispatches from the border.',
      flaws: 'I default to command voice even when collaboration is better.',
      goals: 'Train recruits to survive first contact against monstrous threats.',
      fears: 'Failing those under my protection.',
      age: 67,
      height: '4\'8"',
      weight: '182 lbs',
      eyes: 'Amber',
      skin: 'Weathered tan',
      hair: 'Copper-brown',
      distinguishingMarks: 'A faded spear scar across his left forearm.',
      appearance: 'Compact frame with braided beard rings denoting campaigns.',
      clothingStyle: 'Military-cut wool over reinforced leather.',
      faction: 'Stonewatch Garrison',
      rank: 'Sergeant',
      origin: 'Frontier citadel in the Ironspine Range.',
      definingMoment: 'Held a breached gate with six volunteers through the night.',
      backstory:
        'Bromm enlisted young, rose through merit, and now serves as a veteran drillmaster. He relies on textbook discipline and Battle Master tactics to keep his squad alive.',
      alliesAndOrganizations: 'Captain Helja Runehand; Stonewatch quartermaster corps.',
    },
    portrait: '/assets/images/characters/placeholder_char_card5.jpg',
    allowedSources: ['XPHB'],
    variantRules: {
      optionalClassFeatures: true,
      averageHitPoints: true,
      abilityScoreMethod: 'standard-array',
    },
    asiChoices: [
      {
        id: 'seed-2-asi-4',
        level: 4,
        className: 'Fighter',
        abilityChanges: { strength: 2 },
      },
    ],
    backgroundAsiBlockIndex: 0,
    backgroundAsiChoices: ['strength', 'constitution'],
    provenance: {
      ...createEmptyProvenance(),
      proficiencies: {
        armor: {
          light: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
          medium: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
          heavy: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
          shield: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
        },
        weapons: {
          simple: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
          martial: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
        },
        tools: {
          "smith's tools": [
            {
              sourceType: 'subclass',
              sourceName: 'Battle Master',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Battle Master',
            },
          ],
        },
        languages: {
          common: [
            {
              sourceType: 'race',
              sourceName: 'Dwarf',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Dwarf',
            },
          ],
          dwarvish: [
            {
              sourceType: 'race',
              sourceName: 'Dwarf',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Dwarf',
            },
          ],
          giant: [
            {
              sourceType: 'background',
              sourceName: 'Soldier',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Soldier',
            },
          ],
        },
        skills: {
          athletics: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Fighter',
            },
          ],
          intimidation: [
            {
              sourceType: 'background',
              sourceName: 'Soldier',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Soldier',
            },
          ],
        },
        savingThrows: {
          strength: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
          constitution: [
            {
              sourceType: 'class',
              sourceName: 'Fighter',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Fighter',
            },
          ],
        },
      },
      abilityBonuses: [
        {
          ability: 'strength',
          value: 2,
          sourceTag: {
            sourceType: 'background',
            sourceName: 'Soldier',
            sourceRef: 'XPHB',
            grantType: 'choice',
            label: 'Soldier',
          },
        },
        {
          ability: 'constitution',
          value: 1,
          sourceTag: {
            sourceType: 'background',
            sourceName: 'Soldier',
            sourceRef: 'XPHB',
            grantType: 'choice',
            label: 'Soldier',
          },
        },
      ],
      features: {
        'fighting style': [
          {
            sourceType: 'class',
            sourceName: 'Fighter',
            sourceRef: 'XPHB',
            grantType: 'choice',
            label: 'Fighter',
          },
        ],
      },
    },
    createdAt: BASE_TIME,
    lastModified: BASE_TIME,
  },
  {
    id: 'seed-3',
    version: '1.0.0',
    name: 'Nyxara Voss',
    race: 'Tiefling',
    raceSource: 'PHB',
    class: 'Warlock',
    classSource: 'PHB',
    subclass: 'The Fiend',
    subclassSource: 'PHB',
    background: 'Sage',
    backgroundSource: 'XPHB',
    level: 10,
    experiencePoints: 64000,
    classProgression: [
      {
        name: 'Warlock',
        source: 'PHB',
        levels: 5,
        subclass: 'The Fiend',
        subclassSource: 'PHB',
      },
      {
        name: 'Sorcerer',
        source: 'PHB',
        levels: 5,
        subclass: 'Draconic Bloodline',
        subclassSource: 'PHB',
      },
    ],
    abilityScores: {
      strength: 8,
      dexterity: 14,
      constitution: 14,
      intelligence: 13,
      wisdom: 10,
      charisma: 15,
    },
    proficiencies: {
      armor: ['Light Armor'],
      weapons: ['Simple Weapons', 'Daggers', 'Light Crossbows'],
      tools: ["Calligrapher's Supplies"],
      skills: [],
      languages: ['Common', 'Infernal', 'Draconic', 'Elvish'],
      savingThrows: ['Wisdom', 'Charisma', 'Constitution'],
    },
    features: [
      {
        id: 'dark-ones-blessing',
        name: "Dark One's Blessing",
        source: 'Warlock (The Fiend)',
        description: 'Gain temporary hit points when reducing a hostile creature to 0 HP.',
        level: 1,
      },
      {
        id: 'eldritch-invocations',
        name: 'Eldritch Invocations',
        source: 'Warlock',
        description: "Invocations selected: Agonizing Blast, Devil's Sight, Repelling Blast.",
        level: 2,
      },
      {
        id: 'pact-of-the-tome',
        name: 'Pact Boon (Pact of the Tome)',
        source: 'Warlock',
        description: 'Pact boon selected at warlock level 3.',
        level: 3,
      },
      {
        id: 'draconic-resilience',
        name: 'Draconic Resilience',
        source: 'Sorcerer (Draconic Bloodline)',
        description: 'Base AC and hit point resilience from draconic ancestry.',
        level: 1,
      },
      {
        id: 'font-of-magic',
        name: 'Font of Magic',
        source: 'Sorcerer',
        description: 'Sorcery points available for slot conversion and metamagic.',
        level: 2,
      },
      {
        id: 'metamagic',
        name: 'Metamagic',
        source: 'Sorcerer',
        description: 'Metamagic selected: Quickened Spell, Twinned Spell.',
        level: 3,
      },
      {
        id: 'asi-wlk4',
        name: 'Ability Score Improvement',
        source: 'Warlock',
        description: 'Took +2 Charisma at warlock level 4.',
        level: 4,
      },
      {
        id: 'asi-sor4',
        name: 'Ability Score Improvement',
        source: 'Sorcerer',
        description: 'Took +2 Dexterity at sorcerer level 4.',
        level: 4,
      },
    ],
    feats: [],
    spells: {
      spellProfiles: [
        {
          id: 'class:Warlock|PHB',
          type: 'class',
          label: 'Warlock (Lv 5)',
          className: 'Warlock',
          classSource: 'PHB',
          cantrips: ['Eldritch Blast', 'Mage Hand', 'Minor Illusion'],
          spellsKnown: [
            'Hex',
            'Armor of Agathys',
            'Hellish Rebuke',
            'Misty Step',
            'Darkness',
            'Counterspell',
            'Fireball',
          ],
          preparedSpells: [],
        },
        {
          id: 'class:Sorcerer|PHB',
          type: 'class',
          label: 'Sorcerer (Lv 5)',
          className: 'Sorcerer',
          classSource: 'PHB',
          cantrips: ['Fire Bolt', 'Ray of Frost', 'Prestidigitation', 'Message'],
          spellsKnown: [
            'Shield',
            'Magic Missile',
            'Mirror Image',
            'Scorching Ray',
            'Fly',
            'Hypnotic Pattern',
          ],
          preparedSpells: [],
        },
        {
          id: 'special:unrestricted',
          type: 'special',
          label: 'Special (Unrestricted)',
          cantrips: [],
          spellsKnown: [],
          preparedSpells: [],
          alwaysPrepared: true,
        },
      ],
      spellSlots: {
        level1: { max: 4, used: 0 },
        level2: { max: 3, used: 0 },
        level3: { max: 2, used: 0 },
        level4: { max: 0, used: 0 },
        level5: { max: 0, used: 0 },
        level6: { max: 0, used: 0 },
        level7: { max: 0, used: 0 },
        level8: { max: 0, used: 0 },
        level9: { max: 0, used: 0 },
      },
    },
    equipment: [
      {
        id: 's3-eq1',
        name: 'Rod',
        type: 'G',
        quantity: 1,
        equipped: true,
        source: 'PHB',
      },
      {
        id: 's3-eq2',
        name: 'Dagger',
        type: 'M',
        quantity: 1,
        equipped: true,
        source: 'PHB',
      },
      {
        id: 's3-eq3',
        name: 'Arcane Focus',
        type: 'G',
        quantity: 1,
        equipped: true,
        source: 'PHB',
      },
    ],
    hitPoints: { max: 73, current: 73, temporary: 0 },
    armorClass: 15,
    initiative: 2,
    speed: 30,
    savingThrows: {
      strength: { proficient: false, bonus: -1 },
      dexterity: { proficient: false, bonus: 2 },
      constitution: { proficient: true, bonus: 5 },
      intelligence: { proficient: false, bonus: 1 },
      wisdom: { proficient: true, bonus: 3 },
      charisma: { proficient: true, bonus: 7 },
    },
    skills: {
      arcana: { proficient: true, expertise: false, bonus: 5 },
      deception: { proficient: true, expertise: false, bonus: 7 },
      intimidation: { proficient: true, expertise: false, bonus: 7 },
      investigation: { proficient: true, expertise: false, bonus: 5 },
      persuasion: { proficient: true, expertise: false, bonus: 7 },
      religion: { proficient: true, expertise: false, bonus: 5 },
    },
    details: {
      gender: 'Female',
      alignment: 'Chaotic Neutral',
      lifestyle: 'Comfortable',
      personalityTraits:
        'I annotate everything, including conversations, as if the world were one long thesis.',
      ideals: 'Power should be understood, not feared.',
      bonds: 'A forbidden infernal manuscript is keyed to my bloodline.',
      flaws: 'I bargain first and worry about cost afterward.',
      goals: 'Master both pact and innate magic without surrendering autonomy.',
      fears: 'Becoming a pawn of either my patron or draconic ancestry.',
      age: 29,
      height: '5\'9"',
      weight: '145 lbs',
      eyes: 'Gold-flecked black',
      skin: 'Crimson',
      hair: 'Midnight blue',
      distinguishingMarks: 'Fine silver sigils traced along both horns.',
      physicalDescription: "Long coat lined in infernal script over scholar's attire.",
      patron: 'Bel, Lord of Avernus',
      patronDetails: 'Negotiated for knowledge in exchange for field intelligence.',
      origin: 'Academy quarter of a cosmopolitan trade city.',
      family: 'Estranged from a merchant house that hid infernal ancestry.',
      definingMoment: 'Survived a planar breach by sealing it with improvised sorcery.',
      lifeEvents: 'Expelled from one college, then recruited by a rival occult society.',
      backstory:
        'Nyxara combined formal magical study with a dangerous fiendish pact and draconic sorcerous talent. She now pursues total arcane independence through relentless experimentation.',
      alliesAndOrganizations: 'Obsidian Athenaeum; Professor Irius Keld.',
    },
    portrait: '/assets/images/characters/placeholder_char_card6.jpg',
    allowedSources: ALL_BOOK_SOURCES,
    variantRules: {
      optionalClassFeatures: true,
      averageHitPoints: true,
      abilityScoreMethod: 'custom',
    },
    asiChoices: [
      {
        id: 'seed-3-asi-warlock-4',
        level: 4,
        className: 'Warlock',
        abilityChanges: { charisma: 2 },
      },
      {
        id: 'seed-3-asi-sorcerer-4',
        level: 4,
        className: 'Sorcerer',
        abilityChanges: { dexterity: 2 },
      },
    ],
    provenance: {
      ...createEmptyProvenance(),
      proficiencies: {
        armor: {
          'light armor': [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Warlock',
            },
          ],
        },
        weapons: {
          'simple weapons': [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Warlock',
            },
          ],
        },
        tools: {
          "calligrapher's supplies": [
            {
              sourceType: 'background',
              sourceName: 'Sage',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Sage',
            },
          ],
        },
        languages: {
          common: [
            {
              sourceType: 'race',
              sourceName: 'Tiefling',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Tiefling',
            },
          ],
          infernal: [
            {
              sourceType: 'race',
              sourceName: 'Tiefling',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Tiefling',
            },
          ],
          draconic: [
            {
              sourceType: 'background',
              sourceName: 'Sage',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Sage',
            },
          ],
          elvish: [
            {
              sourceType: 'background',
              sourceName: 'Sage',
              sourceRef: 'XPHB',
              grantType: 'choice',
              label: 'Sage',
            },
          ],
        },
        skills: {
          arcana: [
            {
              sourceType: 'background',
              sourceName: 'Sage',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Sage',
            },
          ],
          deception: [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Warlock',
            },
          ],
          intimidation: [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Warlock',
            },
          ],
          persuasion: [
            {
              sourceType: 'class',
              sourceName: 'Sorcerer',
              sourceRef: 'PHB',
              grantType: 'choice',
              label: 'Sorcerer',
            },
          ],
          religion: [
            {
              sourceType: 'background',
              sourceName: 'Sage',
              sourceRef: 'XPHB',
              grantType: 'fixed',
              label: 'Sage',
            },
          ],
        },
        savingThrows: {
          wisdom: [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Warlock',
            },
          ],
          charisma: [
            {
              sourceType: 'class',
              sourceName: 'Warlock',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Warlock',
            },
          ],
          constitution: [
            {
              sourceType: 'class',
              sourceName: 'Sorcerer',
              sourceRef: 'PHB',
              grantType: 'fixed',
              label: 'Sorcerer',
            },
          ],
        },
      },
      abilityBonuses: [
        {
          ability: 'charisma',
          value: 2,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Tiefling',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Tiefling',
          },
        },
        {
          ability: 'intelligence',
          value: 1,
          sourceTag: {
            sourceType: 'race',
            sourceName: 'Tiefling',
            sourceRef: 'PHB',
            grantType: 'fixed',
            label: 'Tiefling',
          },
        },
      ],
      spells: {
        'eldritch blast': [classSpellTag('Warlock', 'PHB', 1)],
        'mage hand': [classSpellTag('Warlock', 'PHB', 1)],
        'minor illusion': [classSpellTag('Warlock', 'PHB', 3)],
        hex: [classSpellTag('Warlock', 'PHB', 1)],
        'armor of agathys': [classSpellTag('Warlock', 'PHB', 1)],
        'hellish rebuke': [classSpellTag('Warlock', 'PHB', 2)],
        'misty step': [classSpellTag('Warlock', 'PHB', 3)],
        darkness: [classSpellTag('Warlock', 'PHB', 3)],
        counterspell: [classSpellTag('Warlock', 'PHB', 5)],
        fireball: [classSpellTag('Warlock', 'PHB', 5), classSpellTag('Sorcerer', 'PHB', 5)],
        'fire bolt': [classSpellTag('Sorcerer', 'PHB', 1)],
        'ray of frost': [classSpellTag('Sorcerer', 'PHB', 1)],
        prestidigitation: [classSpellTag('Sorcerer', 'PHB', 1)],
        message: [classSpellTag('Sorcerer', 'PHB', 4)],
        shield: [classSpellTag('Sorcerer', 'PHB', 1)],
        'magic missile': [classSpellTag('Sorcerer', 'PHB', 1)],
        'mirror image': [classSpellTag('Sorcerer', 'PHB', 3)],
        'scorching ray': [classSpellTag('Sorcerer', 'PHB', 3)],
        fly: [classSpellTag('Sorcerer', 'PHB', 5)],
        'hypnotic pattern': [classSpellTag('Sorcerer', 'PHB', 5)],
      },
      features: {
        metamagic: [
          {
            sourceType: 'class',
            sourceName: 'Sorcerer',
            sourceRef: 'PHB',
            grantType: 'choice',
            label: 'Sorcerer',
          },
        ],
        'eldritch invocations': [
          {
            sourceType: 'class',
            sourceName: 'Warlock',
            sourceRef: 'PHB',
            grantType: 'choice',
            label: 'Warlock',
          },
        ],
      },
    },
    createdAt: BASE_TIME,
    lastModified: BASE_TIME,
  },
]
